// CONST KEYWORD IS USE TO DECLARE CONSTANT VALUE.
// THE VALUE OF CONSTANT CANNOT BE CHANGE AS IT REMAINS CONSTANT THROUGHOUT THE FILE.
// CONST CANNOT BE REDECLARED LIKE LET KEY WORD.
// YOU CANNOT UNDEFINED CONST EX) const pi; (Invalid)

const pi = 3.14;
console.log(pi);

// YOU CAN PERFORM ARITHMATIC OPERATION IN CONSTANT BUT YOU CANNOT CHANGE ITS VALUE.

console.log(pi * 2); // 3.14 * 2 = 6.28
console.log(pi ** 2); // 3.14 ^ 2 = 9.8596