// DISADVANTAGE OF VARIABLE (VAR) IS THAT YOU CAN USE TWO SAME NAME OF VARIABLE IN THE SAME FILE.

// SOLUTION IS LET KEYWORD.

// LET KEYWORD WORKS SAME AS VARIABLE BUT YOU CANNOT DECLARE TWO SAME NAME OF VARIABLE USING LET KEYWORD. 

// ONCE YOU DECLARED ANY VARIABLE WITH LET KEYWORD THEN YOU CANNOT USE SAME NAME OF VARIBLE EITHER WITH LET OR VAR.

let firstName = "Nehal";
console.log(firstName);

// let firstName = "Pintu"; // firstName has already been declared